Renamed wrong namespace. Removed unused using directives #93
marcominerva/TinyHelpers pull request #101
Opened 2022-10-19 20:55 UTC by pampua84

fixed #93

2022-10-20 13:28 UTC, marcominerva requested changes

2022-10-20 17:00 UTC, pampua84 commented on samples/TinyHelpers.Sample/Program.cs
> +namespace TinyHelpers.Sample
It was automatic refactoring at SonaLlint suggestion.

![image](https://user-images.githubusercontent.com/17255890/197012344-c6557460-5f23-4e0b-902c-14d25d6130a3.png)

2022-10-20 17:03 UTC, marcominerva commented on samples/TinyHelpers.Sample/Program.cs
> +namespace TinyHelpers.Sample
Appliyng Sonarlint suggestions isn't in the scope of the issue, so I ask you ti revert this change.

2022-10-20 17:04 UTC, marcominerva requested changes
Please revert Sonarlint suggestion about Program.cs

2022-10-20 22:09 UTC, pampua84 reviewed
Reverted Sonarlint suggestion about Program.cs

2022-10-20 22:18 UTC, pampua84 reviewed
Reverted Sonarlint suggestion about Program.cs

2022-10-26 19:45 UTC, pampua84 commented
In this commit b9cd12c78caf81a5421bb3f53fb7da2790ac60a8 should i have solved the problem? or am I wrong?

2022-10-26 20:08 UTC, marcominerva commented
Please mark the conversation as resolved and then request a new review.

2022-10-26 20:18 UTC, closed without merging