Add GetAttribute extension method for retrieving attributes fromm Assembly
marcominerva/TinyHelpers pull request #241
Opened 2024-12-19 00:00 UTC by engineering87

Added `GetAttribute` method for Assembly to retrieve attributes applied to the assembly.
The method is generic and accepts a function to extract a specific value from the attribute.

2025-01-15 13:40 UTC, marcominerva requested changes

2025-01-15 13:40 UTC, marcominerva commented on src/TinyHelpers/Extensions/AssemblyExtensions.cs
> +    public static string? GetAttribute<T>(this Assembly assembly, Func<T, string> value) where T : Attribute
The method should return a generic **TValue**, because the property we get from the `Func` can be of any type.

2025-01-15 13:40 UTC, marcominerva commented on src/TinyHelpers/Extensions/AssemblyExtensions.cs
> +        return attribute != null ? value(attribute) : null;
Use pattern matching for `null `check.

2025-01-18 15:36 UTC, engineering87 commented on src/TinyHelpers/Extensions/AssemblyExtensions.cs
> +    public static string? GetAttribute<T>(this Assembly assembly, Func<T, string> value) where T : Attribute
Done

2025-01-18 15:36 UTC, engineering87 commented on src/TinyHelpers/Extensions/AssemblyExtensions.cs
> +        return attribute != null ? value(attribute) : null;
Done

2025-01-20 10:33 UTC, marcominerva requested changes

2025-01-20 10:33 UTC, marcominerva commented on src/TinyHelpers/Extensions/AssemblyExtensions.cs
> +            .GetCustomAttributes(typeof(T), false)
I would prefer to pass the `inherit` argument of `GetCustomAttributes` as an optional parameter  (with `false` default value) of the `GetAttribute` extension method, so this method can handle all the scenarios.

2025-01-20 11:56 UTC, engineering87 commented on src/TinyHelpers/Extensions/AssemblyExtensions.cs
> +            .GetCustomAttributes(typeof(T), false)
Done

2025-01-20 13:49 UTC, merged