Add Repeat string extension
marcominerva/TinyHelpers pull request #77
Opened 2022-04-16 18:56 UTC by kasuken

2022-04-18 09:40 UTC, kasuken commented
> for (int i = 0; i < count; i++)
> 
> non deve essere for (int i = 0; i < times; i++) ?

I think you are seeing an old commit.
In the last commit it's solved that issue.

2022-04-19 07:34 UTC, marcominerva commented on src/TinyHelpers/Extensions/StringExtensions.cs
> +    public static string Repeat(this string str, int times)
Use meaningful variable and parameter names. Replace `str `with `input `(like in the other methods of this class).

2022-04-19 07:44 UTC, marcominerva commented on src/TinyHelpers/Extensions/StringExtensions.cs
> +        var s = new StringBuilder();
Use a meaningful variable name. Replace `s` with something like `result` or `output`.

2022-04-19 07:45 UTC, marcominerva commented on src/TinyHelpers/Extensions/StringExtensions.cs
> +        for (int i = 0; i < times; i++)
replace `int` with `var` (suggestion: use Code Clean Up to automatically follow the guidelines).

2022-04-19 07:47 UTC, marcominerva commented on src/TinyHelpers/Extensions/StringExtensions.cs
> +        return s.ToString();
Missing blank line after curly brace.

2022-04-19 07:49 UTC, marcominerva commented on src/TinyHelpers/Extensions/StringExtensions.cs
> +            s.Append(str);
What happens if `str` is null or `times` is negative? Perhaps it makes sense to add some parameter checks above.

2022-04-19 07:50 UTC, marcominerva requested changes
Please take a look to the comments. Thank you :-)

2022-06-02 14:40 UTC, marcominerva commented
Closed as no reply from the author

2022-06-02 14:40 UTC, closed without merging